### ISSUE TITLE
Double dash

### ISSUE THREAD

**Issue by telemachus** [speedata/optionparser#3]
`--` alone is usually used to indicate the end of options and that flag parsing should stop.  For example, [the POSIX guidelines here (in guideline 10)](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) say, "The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character." and [Go's stdlib flag package](https://pkg.go.dev/flag) says, "Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--"."

At the moment, optionparser treats `--` as an unknown option. This causes parsing to stop and an error to be returned. Would you consider an enhancement that treats `--` as the standard "end-of-options" marker? (I understand that this may be considered a breaking change.)

**Comment by pgundlach** [comment]
Handling double dash would be great! I don't think this will break anything, as you say the parser stops with an error.

**Comment by telemachus** [comment]
> Handling double dash would be great! I don't think this will break anything, as you say the parser stops with an error.

Terrific. This may be a bit more involved than the last few changes. I will work on it when I can, but probably not right away. (I also have one other small change to submit before I get to work on the larger issue of `--`.)
